drop table if exists author_to_book;
drop table if exists author;
drop table if exists book;
drop table if exists genre;
create table genre(
id bigint generated by default as identity primary key,
genre_name varchar(255)
 );
create table book(
id bigint generated by default as identity primary key,
book_name varchar(255),
genre_id bigint references Genre(id)
);
create table author(
id bigint generated by default as identity primary key,
author_name varchar(255)
);
create table author_to_book(
author_id bigint not null references author(id),
book_id bigint not null references book(id)
);