drop table if exists author_to_book;
drop table if exists author;
drop table if exists book_comment;
drop table if exists book;
drop table if exists genre;
drop table if exists user_;
create table user_(
id bigint generated by default as identity primary key,
name varchar(255),
pass varchar(255)
);
create table genre(
id bigint generated by default as identity primary key,
genre_name varchar(255)
 );
create table book(
id bigint generated by default as identity primary key,
book_name varchar(255),
genre_id bigint references genre(id)
);
create table book_comment(
id bigint generated by default as identity primary key,
comment varchar(255),
book_id bigint references book(id)
);
create table author(
id bigint generated by default as identity primary key,
author_name varchar(255)
);
create table author_to_book(
author_id bigint not null references author(id),
book_id bigint not null references book(id)
);
